//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Register
    {
        public int Id { get; set; }
        public int LessonId { get; set; }
        public int StudentId { get; set; }
        public int Score { get; set; }
    
        public virtual Tbl_Lesson Tbl_Lesson { get; set; }
        public virtual Tbl_Student Tbl_Student { get; set; }
    }
}
